-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 23:12:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema doacoes_sangue
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doacoes_sangue
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doacoes_sangue` DEFAULT CHARACTER SET utf8 ;
USE `doacoes_sangue` ;

-- -----------------------------------------------------
-- Table `doacoes_sangue`.`Doadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doacoes_sangue`.`Doadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `idade` INT NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `tipo_sanguineo` ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-') NOT NULL,
  `telefone` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `ultima_doacao` DATE NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `status` ENUM('Ativo', 'Inativo') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doacoes_sangue`.`Hospitais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doacoes_sangue`.`Hospitais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(30) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `responsavel` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doacoes_sangue`.`Doacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doacoes_sangue`.`Doacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_doacao` DATE NOT NULL,
  `quantidade_ml` INT NOT NULL,
  `tipo_sanguineo` ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-') NOT NULL,
  `hospital_id` INT NOT NULL,
  `doador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doacoes_hospital_idx` (`hospital_id` ASC) VISIBLE,
  INDEX `fk_doacoes_doador_idx` (`doador_id` ASC) VISIBLE,
  CONSTRAINT `fk_doacoes_hospital`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `doacoes_sangue`.`Hospitais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_doacoes_doador`
    FOREIGN KEY (`doador_id`)
    REFERENCES `doacoes_sangue`.`Doadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doacoes_sangue`.`Solicitacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doacoes_sangue`.`Solicitacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_sanguineo` ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-') NOT NULL,
  `quantidade_ml` INT NOT NULL,
  `data_solicitacao` DATE NOT NULL,
  `status` ENUM('Pendente', 'Atendida', 'Cancelada') NOT NULL,
  `hospital_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_solicitacoes_hospital_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_solicitacoes_hospital`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `doacoes_sangue`.`Hospitais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doacoes_sangue`.`Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doacoes_sangue`.`Pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `data_transfusao` DATE NOT NULL,
  `hospital_id` INT NOT NULL,
  `solicitacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pacientes_hospital_idx` (`hospital_id` ASC) VISIBLE,
  INDEX `fk_pacientes_solicitacao_idx` (`solicitacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_pacientes_hospital`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `doacoes_sangue`.`Hospitais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pacientes_solicitacao`
    FOREIGN KEY (`solicitacao_id`)
    REFERENCES `doacoes_sangue`.`Solicitacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doacoes_sangue`.`Estoques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doacoes_sangue`.`Estoques` (
  `tipo_sanguineo` ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-') NOT NULL,
  `quantidade_ml` INT NOT NULL,
  `hospital_id` INT NOT NULL,
  INDEX `fk_estoques_hospital_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_estoques_hospital`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `doacoes_sangue`.`Hospitais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
